### ISSUE TITLE
Similar Kindle dashboard

### ISSUE THREAD

**Issue by niutech** [bukowskiadam/kindle-page#1]
Nice project! Also check out my [Kindle dashboard](https://github.com/niutech/kindle-dashboard) and [Kindle VNC](https://github.com/niutech/kindle-vnc) using only web browser.

Your project does a screenshot of a `status-page.html` but how do you show it on Kindle? Using web browser too, without jailbreaking Kindle?

**Comment by bukowskiadam** [comment]
Thanks! I rejected the option of using the built-in browser because of two reasons:
1. I wanted to save those precious pixels at the top.
2. Battery life.

My kindle is in the picture frame, and it lasts more than 2 weeks running the dashboard (with it's rather worn 10 years old battery). How is your battery life when you run the built-in browser?

I like how you solved Airly data. Do you have an API key or do you scrape their data from the page?

Didn't you have problems with SSL? I noticed that many web pages didn't load in the built-in browser. Probably your server handles the old vulnerable TLS which is not supported on Vercel 😉 

Here is how it looks now:

![20221001_175650](https://user-images.githubusercontent.com/1633333/194003173-e737b503-8c30-4e28-8b6c-5222d6a2b151.jpg)

**Comment by niutech** [comment]
Thanks for the reply. My Kindle is always charging, so the battery life is not an issue. I am using a free Airly API key. I don't have problems with [Kindle dashboard](https://old.juvenia.info/kindle/) hosted on OVH. You don't even need HTTPS for public data, HTTP is enough.
